name: C/C++ CI

on:
  push:
    branches: [ "lineage-15.1" ]
  pull_request:
    branches: [ "lineage-15.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -j8
    - name: make check
      run: make check
    - name: mkbootimg
      run: ./mkbootimg.sh
